steps:
  - script: |
     # Authenticate GitHub CLI
          echo $GITHUB_TOKEN | gh auth login --with-token
          echo "Fetching details of the last commit in the current CI triggered pull request..."
          accessToken="$(Ranjithgithubtoken)"
          # accessToken="$(System.AccessToken)"
          repository="$BUILD_REPOSITORY_NAME"
          repoName=$(echo "$repository" | awk -F '/' '{print $2}')
          orgName=$(echo "$repository" | awk -F '/' '{print $1}')
          
          # lastMergedPRId="$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER"
          # lastMergedPRId="$(system.pullRequest.pullRequestNumber)"
          lastMergedPRId=$(curl -s -H "Authorization: Bearer $accessToken" "https://api.github.com/repos/$repository/pulls?state=closed" | jq -r '.[0].number')
          echo "last Commit SHA : $lastMergedPRId"
          echo "##vso[task.setvariable variable=MergedID]$lastMergedPRId"
          pullRequestDetails=$(curl -s -H "Authorization: Bearer $accessToken"  "https://api.github.com/repos/$repository/pulls/$lastMergedPRId")
          # echo "pull Request Details: $pullRequestDetails"
          lastCommitSHA=$(echo "$pullRequestDetails" | jq -r '.merge_commit_sha')
          # lastCommitSHA=$(echo "$pullRequestDetails" | jq -r '.head.sha')
          echo "last Commit SHA : $lastCommitSHA"
     gh api /repos/$(Build.Repository.Name)/commits/$lastCommitSHA/comments --method POST --field "body=$COMMENT"
    displayName: 'Post results to GitHub PR'