# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: sourcesitename
  displayName: Please enter the sourcesite name like "https://<App_Base URL>/bi/site/<Site Name>"
  #type: string
- name: targetsitename
  displayName: Please enter the targetsite name like "https://<App_Base URL>/bi/site/<Site Name>"
  #type: string
- name: DashboardIDs
  displayName: Please enter the dashboard IDs (comma-separated). Enter "All" for all dashboards.
  type: string
  default: All
- name: categodyID
  displayName: Please enter the catogory ID.
  type: string

pool:
  vmImage: Windows-latest

jobs:

- job: GetBearerToken
  steps:
  - powershell: |
      $apiUrl = "${{ parameters.sourcesitename }}/token"  # URL to get bearer token
      $credentials = @{
          grant_type = "password"
          username = "admin"
          password = "Admin@123"
      }
      
      $tokenResponse = Invoke-RestMethod -Uri $apiUrl -Method Post -Body $credentials

      # Debugging line to inspect the authentication response
      Write-Host "Authentication Response: $($tokenResponse | ConvertTo-Json -Depth 10)"
      $bearerToken = $tokenResponse.access_token

      # Store the access token in a new variable
      $storedAccessToken = $bearerToken

      echo "$storedAccessToken"
      echo "##vso[task.setvariable variable=Bearertoken]$storedAccessToken"
    displayName: 'Get Bearer Token and Send POST Request for source machine'
     
  - powershell: |
      $apiEndpoint = "${{ parameters.sourcesitename }}/v4.0/dashboards"  # API endpoint
      $bearerToken = "$(Bearertoken)"  # Access the pipeline variable
      echo "$(Bearertoken)"
      $headers = @{
          "Authorization" = "Bearer $bearerToken"
      }

      try {
          # Send the GET request using the bearer token
          $response = Invoke-RestMethod -Uri $apiEndpoint -Method Get -Headers $headers
          Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
      } catch {
          Write-Host "Error: $($_.Exception.Message)"
      }
      # Extract the "Id" values from the response
      $idsArray = @()
      foreach ($item in $response.Data) {
          $idsArray += $item.Id
      }

      # Display the extracted IDs
      Write-Host "Extracted IDs: $($idsArray -join ',')"
      $Idarray = $($idsArray -join ',')
      echo $Idarray
      echo "##vso[task.setvariable variable=Idarray1]$Idarray"
      $apiUrl1 = "${{ parameters.sourcesitename }}/v4.0/dashboards/download/job"  # API endpoint
      $bearerToken = "$(Bearertoken)"  # Access the pipeline variable

      $headers = @{
          "Authorization" = "Bearer $bearerToken"
          "Content-Type" = "application/json"
      }
      $dashboardIdsArray = @()
      if (${{ parameters.DashboardIDs }} -eq "All") {
          $dashboardIdsArray = $Idarray -split ','
          $dashboardIdsArray = $dashboardIdsArray -replace '^"|"$', '"$0"'
      } else {
          $dashboardIdsArray = ${{ parameters.DashboardIDs }} -split ','
          $dashboardIdsArray = $dashboardIdsArray -replace '^"|"$', '"$0"'
      }
      echo $dashboardIdsArray

      # Construct the request body with the Dashboard IDs
      $requestBody = @{
          "DashboardId" = $dashboardIdsArray
          "CanIncludeSensitiveInformation" = $true
      }

      # Convert the request body to JSON format
      $requestBodyJson = $requestBody | ConvertTo-Json -Depth 10

      # Send the POST request using the bearer token and request body
      $response = Invoke-RestMethod -Uri $apiUrl1 -Method Post -Headers $headers -Body $requestBodyJson

      # Display the response
      Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
      # Extract the JobId from the response and store it in another variable
      $jobId = $response.Data.JobId

      Write-Host "Extracted JobId: $jobId"
      Write-Host "##vso[task.setvariable variable=jobid]$jobId"
      $downloadUrl = "${{ parameters.sourcesitename }}/v4.0/dashboards/download/job/$jobId"
      Write-Host "Download URL: $downloadUrl"

    displayName: 'Get the JOB ID for downlaod the dashboard'
  - powershell: |
      $apiUrl0 = "${{ parameters.sourcesitename }}/v4.0/dashboards/download/job/$(jobid)"  # Replace with your API endpoint
      $bearerToken = "$(Bearertoken)"  # Access the pipeline variable

      $headers = @{
          "Authorization" = "Bearer $bearerToken"
          "Content-Type" = "application/json"
      }

      # Send the GET request using the bearer token
      $response = Invoke-RestMethod -Uri $apiUrl0 -Method Get -Headers $headers

      # Display the response
      Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
     
      $itemContent = $response.Data.ItemContent
      $itemExtension = $response.Data.ItemExtension

      $apiUrl = "${{ parameters.sourcesitename }}/v4.0/dashboards/upload/meta"  # Replace with your API endpoint
      $bearerToken = "$(Bearertoken)"  # Access the pipeline variable

      $headers = @{
          "Authorization" = "Bearer $bearerToken"
          "Content-Type" = "application/json"
      }
      # Construct the request body
      $requestBody = @{
          "FileContent" = $itemContent
          "FileExtension" = $itemExtension
      }
      # Convert the request body to JSON format
      $requestBodyJson = $requestBody | ConvertTo-Json -Depth 10

      # Send the POST request using the bearer token and request body
      $response = Invoke-RestMethod -Uri $apiUrl -Method Post -Headers $headers -Body $requestBodyJson
      # Extract the "Data" values and store them in a new variable
      $dataValues = $response.Data
      # Display the response
      Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
    
      $apiUrl1 = "${{ parameters.targetsitename }}/token"  # URL to get bearer token
      $credentials = @{
          grant_type = "password"
          username = "admin"
          password = "Admin@123"
      }
      
      $tokenResponse = Invoke-RestMethod -Uri $apiUrl1 -Method Post -Body $credentials

      # Debugging line to inspect the authentication response
      Write-Host "Authentication Response: $($tokenResponse | ConvertTo-Json -Depth 10)"
      $bearerToken = $tokenResponse.access_token
      # Store the access token in a new variable
      $storedAccessToken = $bearerToken
      echo "##vso[task.setvariable variable=Bearertokentarget]$storedAccessToken"
      $apiUrl2 = "${{ parameters.targetsitename }}/v4.0/categories"  # Replace with your API endpoint
      $bearerToken = "$storedAccessToken"  # Access the pipeline variable
      $headers = @{
          "Authorization" = "Bearer $bearerToken"
          "Content-Type" = "application/json"
      }
      # Send the GET request using the bearer token
      $response = Invoke-RestMethod -Uri $apiUrl2 -Method Get -Headers $headers
      # Display the response
      Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
      $apiUrl3 = "${{ parameters.targetsitename }}/v4.0/dashboards/upload"  # Replace with your API endpoint
      $bearerToken = "$storedAccessToken"  # Access the pipeline variable
      $headers = @{
          "Authorization" = "Bearer $bearerToken"
          "Content-Type" = "application/json"
      }
      # Request Body for this api
      $request = @{
          "ItemContent" = $itemContent
          "ItemExtension" = $itemExtension
          "CategoryId" = ${{ parameters.categodyID }}
          "ItemMetaInfo" = $dataValues
           }
      # Display the constructed request body
      $requestBodyJson = $request | ConvertTo-Json -Depth 10

      # Send the GET request using the bearer token
      $response = Invoke-RestMethod -Uri $apiUrl3 -Method Post -Headers $headers -Body $requestBodyJson

      # Display the response
      Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
      # Extract the Job ID
      $jobId = $response.Data.JobId
      
      $apiUrl4 = "${{ parameters.targetsitename }}/v4.0/dashboards/upload/job/$jobId"  # Replace with your API endpoint
      $bearerToken = "$storedAccessToken"  # Access the pipeline variable

      $headers = @{
          "Authorization" = "Bearer $bearerToken"
          "Content-Type" = "application/json"
      }
      $response = Invoke-RestMethod -Uri $apiUrl4 -Method Get -Headers $headers 
      Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
      # Wait for 10 seconds
      Start-Sleep -Seconds 10
      $response = Invoke-RestMethod -Uri $apiUrl4 -Method Get -Headers $headers 
      Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
      # Wait for 10 seconds
      Start-Sleep -Seconds 10
      $response = Invoke-RestMethod -Uri $apiUrl4 -Method Get -Headers $headers 
      Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
      # Wait for 10 seconds
      Start-Sleep -Seconds 10
      $response = Invoke-RestMethod -Uri $apiUrl4 -Method Get -Headers $headers 
      Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
  displayName: 'Upload the dashboard'