pool: 
  vmImage: 'windows-server'
steps:
  - task: PublishToAzureServiceBus@2
    inputs:
      azureSubscription: 'SF3358-Bold BI-DevOps-Ranjithkumar(d85cca03-706a-4ff7-81bf-d0a90d9bc685)'
      serviceBusQueueName: 'ranjith'
      serviceBusNamespace: 'ranjithtesting'
      messageBody: 'Message vandhruchae'
      signPayload: false
      waitForCompletion: false
      useDataContractSerializer: false

  

  