# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:

- job: GetBearerToken
  steps:
  - powershell: |
      $apiUrl = "https://hotfix-linux.boldbi.com/api/site/test/token"
      $username = "Admin"
      $password = "Admin@123"

      $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("${username}:${password}")))

      $headers = @{
        Authorization = "Basic $base64AuthInfo"
      }

      $response = Invoke-RestMethod -Uri $apiUrl -Method Post -Headers $headers

      # Extract the bearer token from the response and store it in a variable
      $token = $response.access_token
      Write-Host "##vso[task.setvariable variable=BearerToken;issecret=true]$token"

    displayName: 'Get Bearer Token'

  - script: |
      apiUrl="https://hotfix-linux.boldbi.com/server-api-reference/v4.0/api-reference/#operation/Dashboards_GetDashboards"
      response=$(curl -s "$apiUrl")

      # Store the response in a pipeline variable
      echo "##vso[task.setvariable variable=ApiResponse;isOutput=true]$response"
    
    displayName: 'Call API and Store Response'


