# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: CallApiAndStoreResponse
  steps:
  - script: |
      apiUrl="https://hotfix-linux.boldbi.com/server-api-reference/v4.0/api-reference/#operation/Dashboards_GetDashboards"
      response=$(curl -s "$apiUrl")

      # Store the response in a pipeline variable
      echo "##vso[task.setvariable variable=ApiResponse;isOutput=true]$response"
    
    displayName: 'Call API and Store Response'


