# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:

- job: GetBearerToken
  steps:
  - powershell: |
      $apiUrl = "https://hotfix-docker.boldbi.com/bi/api/site/site1/token"  # URL to get bearer token
      $credentials = @{
          grant_type: "password"
          username = "admin"
          password = "Admin@123"
      }
      
      $tokenResponse = Invoke-RestMethod -Uri $apiUrl -Method Post -Body $credentials

      # Debugging line to inspect the authentication response
      Write-Host "Authentication Response: $($tokenResponse | ConvertTo-Json -Depth 10)"

      $bearerToken = $tokenResponse.access_token

      $apiEndpoint = "https://hotfix-docker.boldbi.com/bi/api/site/site1/token"  # API endpoint
      $headers = @{
          "Authorization" = "Bearer $bearerToken"
      }

      # Send the POST request using the bearer token
      $postData = @{
          key1 = "value1"
          key2 = "value2"
      }
      $response = Invoke-RestMethod -Uri $apiEndpoint -Method Post -Headers $headers -Body $postData

      Write-Host "API Response: $response"

    displayName: 'Get Bearer Token and Send POST Request'


