# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
parameters:
- name: DashboardIDs
  displayName: Please enter the dashboard IDs (comma-separated). Enter "All" for all dashboards.
  type: string
  default: All
- name: categodyID
  displayName: Please enter the catogory ID.
  type: string
pool:
  vmImage: ubuntu-latest

jobs:

- job: GetBearerToken
  steps:
  - powershell: |
      $apiUrl = "https://hotfix-docker.boldbi.com/bi/api/site/site1/token"  # URL to get bearer token
      $credentials = @{
          grant_type = "password"
          username = "admin"
          password = "Admin@123"
      }
      
      $tokenResponse = Invoke-RestMethod -Uri $apiUrl -Method Post -Body $credentials

      # Debugging line to inspect the authentication response
      Write-Host "Authentication Response: $($tokenResponse | ConvertTo-Json -Depth 10)"
      $bearerToken = $tokenResponse.access_token

      # Store the access token in a new variable
      $storedAccessToken = $bearerToken

      echo "$storedAccessToken"
      echo "##vso[task.setvariable variable=Bearertoken]$storedAccessToken"
    displayName: 'Get Bearer Token and Send POST Request for source machine'
     
  - powershell: |
      $apiEndpoint = "https://hotfix-docker.boldbi.com/bi/api/site/site1/v4.0/dashboards"  # API endpoint
      $bearerToken = "$(Bearertoken)"  # Access the pipeline variable
      echo "$(Bearertoken)"
      $headers = @{
          "Authorization" = "Bearer $bearerToken"
      }

      try {
          # Send the GET request using the bearer token
          $response = Invoke-RestMethod -Uri $apiEndpoint -Method Get -Headers $headers
          Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
      } catch {
          Write-Host "Error: $($_.Exception.Message)"
      }
      # Extract the "Id" values from the response
      $idsArray = @()
      foreach ($item in $response.Data) {
          $idsArray += $item.Id
      }

      # Display the extracted IDs
      Write-Host "Extracted IDs: $($idsArray -join ',')"
      $Idarray = $($idsArray -join ',')
      echo $Idarray
      echo "##vso[task.setvariable variable=Idarray1]$Idarray"
      $apiUrl1 = "https://hotfix-docker.boldbi.com/bi/api/site/site1/v4.0/dashboards/download/job"  # API endpoint
      $bearerToken = "$(Bearertoken)"  # Access the pipeline variable

      $headers = @{
          "Authorization" = "Bearer $bearerToken"
          "Content-Type" = "application/json"
      }
      $dashboardIdsArray = @()
      if (${{ parameters.DashboardIDs }} -eq "All") {
          $dashboardIdsArray = $Idarray -split ','
          $dashboardIdsArray = $dashboardIdsArray -replace '^"|"$', '"$0"'
      } else {
          $dashboardIdsArray = ${{ parameters.DashboardIDs }} -split ','
          $dashboardIdsArray = $dashboardIdsArray -replace '^"|"$', '"$0"'
      }
      echo $dashboardIdsArray

      # Construct the request body with the Dashboard IDs
      $requestBody = @{
          "DashboardId" = $dashboardIdsArray
          "CanIncludeSensitiveInformation" = $true
      }

      # Convert the request body to JSON format
      $requestBodyJson = $requestBody | ConvertTo-Json -Depth 10

      # Send the POST request using the bearer token and request body
      $response = Invoke-RestMethod -Uri $apiUrl1 -Method Post -Headers $headers -Body $requestBodyJson

      # Display the response
      Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
      # Extract the JobId from the response and store it in another variable
      $jobId = $response.Data.JobId

      Write-Host "Extracted JobId: $jobId"
      Write-Host "##vso[task.setvariable variable=jobid]$jobId"
      $downloadUrl = "https://hotfix-docker.boldbi.com/bi/api/site/site1/v4.0/dashboards/download/job/$jobId"
      Write-Host "Download URL: $downloadUrl"

    displayName: 'Get the JOB ID for downlaod the dashboard'
  - powershell: |
      $apiUrl = "https://hotfix-docker.boldbi.com/bi/api/site/site1/v4.0/dashboards/download/job/$(jobid)"  # Replace with your API endpoint
      $bearerToken = "$(Bearertoken)"  # Access the pipeline variable

      $headers = @{
          "Authorization" = "Bearer $bearerToken"
          "Content-Type" = "application/json"
      }

      # Send the GET request using the bearer token
      $response = Invoke-RestMethod -Uri $apiUrl -Method Get -Headers $headers

      # Display the response
      Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
     
      $itemContent = $response.Data.ItemContent
      $itemExtension = $response.Data.ItemExtension

      Write-Host "ItemContent: $itemContent"
      Write-Host "ItemExtension: $itemExtension"

      Write-Host "##vso[task.setvariable variable=itemcontent]$itemContent"
      Write-Host "##vso[task.setvariable variable=itemExtension]$itemExtension"

    displayName: 'Download the dashboard'
  - powershell: |
      $apiUrl = "https://hotfix-docker.boldbi.com/bi/api/site/site1/v4.0/dashboards/upload/meta"  # Replace with your API endpoint
      $bearerToken = "$(Bearertoken)"  # Access the pipeline variable

      $headers = @{
          "Authorization" = "Bearer $bearerToken"
          "Content-Type" = "application/json"
      }
      $secureContent = "$(itemcontent)"
      # Construct the request body
      $requestBody = @{
          "FileContent" = $secureContent
          "FileExtension" = "$(itemExtension)"
      }
      # Convert the request body to JSON format
      $requestBodyJson = $requestBody | ConvertTo-Json -Depth 10

      # Send the POST request using the bearer token and request body
      $response = Invoke-RestMethod -Uri $apiUrl -Method Post -Headers $headers -Body $requestBodyJson
      # Extract the "Data" values and store them in a new variable
      $dataValues = $response.Data
      # Display the response
      Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
      echo "rk"
      echo $dataValues
      echo "##vso[task.setvariable variable=dataValuesapi]$dataValues"
      $apiUrl1 = "https://hotfix-linux.boldbi.com/bi/api/site/test/token"  # URL to get bearer token
      $credentials = @{
          grant_type = "password"
          username = "admin"
          password = "Admin@123"
      }
      
      $tokenResponse = Invoke-RestMethod -Uri $apiUrl1 -Method Post -Body $credentials

      # Debugging line to inspect the authentication response
      Write-Host "Authentication Response: $($tokenResponse | ConvertTo-Json -Depth 10)"
      $bearerToken = $tokenResponse.access_token

      # Store the access token in a new variable
      $storedAccessToken = $bearerToken

      echo "$storedAccessToken"
      echo "##vso[task.setvariable variable=Bearertokentarget]$storedAccessToken"
      $apiUrl2 = "https://hotfix-linux.boldbi.com/bi/api/site/test/v4.0/categories"  # Replace with your API endpoint
      $bearerToken = "$storedAccessToken"  # Access the pipeline variable

      $headers = @{
          "Authorization" = "Bearer $bearerToken"
          "Content-Type" = "application/json"
      }

      # Send the GET request using the bearer token
      $response = Invoke-RestMethod -Uri $apiUrl2 -Method Get -Headers $headers
      # Display the response
      Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
      echo $dataValuesapi
      $dataValues = $dataValues | ConvertTo-Json -Depth 10
      echo $dataValues
      $dataJson = $dataValues | ConvertTo-Json -Depth 10
      echo $dataJson
      $apiUrl3 = "https://hotfix-linux.boldbi.com/bi/api/site/test/v4.0/dashboards/upload"  # Replace with your API endpoint
      $bearerToken = "$storedAccessToken"  # Access the pipeline variable

      $headers = @{
          "Authorization" = "Bearer $bearerToken"
          "Content-Type" = "application/json"
      }
      echo $dataValues
      $dataJson = $dataValues | ConvertTo-Json -Depth 10
      echo $dataJson
      # Request Body for this api
      $requestBody = @{
          "FileContent" = $secureContent
          "FileExtension" = "$(itemExtension)"
          "CategoryId" = ${{ parameters.categodyID }}
            "ItemMetaInfo" = 
             $dataJson
        }
      # Send the GET request using the bearer token
      $response = Invoke-RestMethod -Uri $apiUrl3 -Method Get -Headers $headers

      # Display the response
      Write-Host "API Response: $($response | ConvertTo-Json -Depth 10)"
  displayName: 'Upload the dashboard'